export enum MetadataKeys {
  DESIGN_TYPES = 'design:type',
  DESIGN_PARAM_TYPES = 'design:paramtypes',
  DESIGN_RETURN_TYPE = 'design:returntype',

  DY_CLASS_CONSTRUCTOR_INJECTION = 'DY_CLASS_CONSTRUCTOR_INJECTION',
  DY_INJECTOR_RESOURCE_PARAMETER = 'DY_INJECTOR_RESOURCE_PARAMETER',
  DY_INJECTOR_RESOURCE = 'DY_INJECTOR_RESOURCE',
}